package fr.kalipso.valorsky.commands;

import fr.kalipso.valorsky.data.command.ProfileCommand;
import fr.kalipso.valorsky.data.command.subcommand.ProfileSaveCommand;
import fr.kalipso.valorsky.manager.Manager;
import fr.kalipso.valorsky.manager.anvil.command.AnvilCommand;
import fr.kalipso.valorsky.manager.back.command.BackCommand;
import fr.kalipso.valorsky.manager.bottlexp.command.BottlexpCommand;
import fr.kalipso.valorsky.manager.broadcast.command.BroadcastCommand;
import fr.kalipso.valorsky.manager.broadcast.command.PubCommand;
import fr.kalipso.valorsky.manager.clearinventory.command.ClearInventoryCommand;
import fr.kalipso.valorsky.manager.condense.command.CondenseCommand;
import fr.kalipso.valorsky.manager.craft.command.CraftCommand;
import fr.kalipso.valorsky.manager.economy.gemmes.command.GemmesCommand;
import fr.kalipso.valorsky.manager.economy.gemmes.command.subcommand.GemmesAddCommand;
import fr.kalipso.valorsky.manager.economy.gemmes.command.subcommand.GemmesResetCommand;
import fr.kalipso.valorsky.manager.economy.gemmes.command.subcommand.GemmesSetCommand;
import fr.kalipso.valorsky.manager.economy.gemmes.command.subcommand.GemmesTakeCommand;
import fr.kalipso.valorsky.manager.economy.vault.command.EconomyCommand;
import fr.kalipso.valorsky.manager.enchant.command.EnchantCommand;
import fr.kalipso.valorsky.manager.enderchest.command.EnderchestCommand;
import fr.kalipso.valorsky.manager.feed.command.FeedCommand;
import fr.kalipso.valorsky.manager.fly.command.FlyCommand;
import fr.kalipso.valorsky.manager.furnace.command.FurnaceCommand;
import fr.kalipso.valorsky.manager.gamemode.command.GamemodeCommand;
import fr.kalipso.valorsky.manager.give.command.GiveCommand;
import fr.kalipso.valorsky.manager.god.command.GodCommand;
import fr.kalipso.valorsky.manager.heal.command.HealCommand;
import fr.kalipso.valorsky.manager.home.command.HomeCommand;
import fr.kalipso.valorsky.manager.home.command.subcommand.HomeDeleteCommand;
import fr.kalipso.valorsky.manager.home.command.subcommand.HomeListCommand;
import fr.kalipso.valorsky.manager.home.command.subcommand.HomeSetCommand;
import fr.kalipso.valorsky.manager.home.command.subcommand.HomeSetmaxCommand;
import fr.kalipso.valorsky.manager.infos.command.InfosCommand;
import fr.kalipso.valorsky.manager.kill.command.KillCommand;
import fr.kalipso.valorsky.manager.kits.commands.KitsCommand;
import fr.kalipso.valorsky.manager.kits.commands.subcommand.KitsCreateCommand;
import fr.kalipso.valorsky.manager.kits.commands.subcommand.KitsDeleteCommand;
import fr.kalipso.valorsky.manager.kits.commands.subcommand.KitsPreviewCommand;
import fr.kalipso.valorsky.manager.list.command.ListCommand;
import fr.kalipso.valorsky.manager.mail.command.MailCommand;
import fr.kalipso.valorsky.manager.mail.command.subcommand.MailTestCommand;
import fr.kalipso.valorsky.manager.nick.command.NickCommand;
import fr.kalipso.valorsky.manager.nick.command.subcommand.NickRemoveCommand;
import fr.kalipso.valorsky.manager.poubelle.command.PoubelleCommand;
import fr.kalipso.valorsky.manager.privatemessage.command.IgnoreCommand;
import fr.kalipso.valorsky.manager.repair.command.RepairCommand;
import fr.kalipso.valorsky.manager.repair.command.subcommand.RepairAllCommand;
import fr.kalipso.valorsky.manager.repair.command.subcommand.RepairHandCommand;
import fr.kalipso.valorsky.manager.seen.command.SeenCommand;
import fr.kalipso.valorsky.manager.spawn.command.SpawnCommand;
import fr.kalipso.valorsky.manager.spawn.command.subcommand.SpawnSetCommand;
import fr.kalipso.valorsky.manager.speed.command.SpeedCommand;
import fr.kalipso.valorsky.manager.teleport.command.TeleportCommand;
import fr.kalipso.valorsky.manager.teleport.command.subcommand.*;
import fr.kalipso.valorsky.manager.time.command.TimeDayCommand;
import fr.kalipso.valorsky.manager.time.command.TimeNightCommand;
import fr.kalipso.valorsky.manager.top.command.TopCommand;
import fr.kalipso.valorsky.manager.vanish.command.VanishCommand;
import fr.kalipso.valorsky.manager.warp.command.WarpCommand;
import fr.kalipso.valorsky.manager.warp.command.subcommand.WarpCreateCommand;
import fr.kalipso.valorsky.manager.warp.command.subcommand.WarpDeleteCommand;
import fr.kalipso.valorsky.manager.warp.command.subcommand.WarpListCommand;
import fr.kalipso.valorsky.placeholder.voteparty.command.VotepartyCommand;
import fr.kalipso.valorsky.placeholder.voteparty.command.subcommand.VotepartyAddCommand;
import fr.kalipso.valorsky.utils.command.CommandFramework;

public class CommandsLoader extends Manager {

    private CommandFramework commandFramework;

    public CommandsLoader()
    {
        this.commandFramework = new CommandFramework(this.getInstance());
        this.registerCommands();
    }

    public void registerCommands()
    {
        this.commandFramework.registerCommands(new ProfileSaveCommand());
        this.commandFramework.registerCommands(new ProfileCommand());
        this.commandFramework.registerCommands(new SpawnCommand());
        this.commandFramework.registerCommands(new SpawnSetCommand());
        this.commandFramework.registerCommands(new GodCommand());
        this.commandFramework.registerCommands(new ListCommand());
        this.commandFramework.registerCommands(new CraftCommand());
        this.commandFramework.registerCommands(new EnderchestCommand());
        this.commandFramework.registerCommands(new BackCommand());
        this.commandFramework.registerCommands(new BroadcastCommand());
        this.commandFramework.registerCommands(new GamemodeCommand());
        this.commandFramework.registerCommands(new SeenCommand());
        this.commandFramework.registerCommands(new HealCommand());
        this.commandFramework.registerCommands(new AnvilCommand());
        this.commandFramework.registerCommands(new BottlexpCommand());
        this.commandFramework.registerCommands(new FeedCommand());
        this.commandFramework.registerCommands(new FurnaceCommand());
        this.commandFramework.registerCommands(new InfosCommand());
        this.commandFramework.registerCommands(new KillCommand());
        this.commandFramework.registerCommands(new WarpCommand());
        this.commandFramework.registerCommands(new WarpListCommand());
        this.commandFramework.registerCommands(new WarpCreateCommand());
        this.commandFramework.registerCommands(new WarpDeleteCommand());
        this.commandFramework.registerCommands(new NickCommand());
        this.commandFramework.registerCommands(new NickRemoveCommand());
        this.commandFramework.registerCommands(new TeleportCommand());
        this.commandFramework.registerCommands(new TeleportAcceptCommand());
        this.commandFramework.registerCommands(new TeleportCoordsCommand());
        this.commandFramework.registerCommands(new TeleportDenyCommand());
        this.commandFramework.registerCommands(new TeleportHereCommand());
        this.commandFramework.registerCommands(new TeleportRequestCommand());
        this.commandFramework.registerCommands(new PoubelleCommand());
        this.commandFramework.registerCommands(new SpeedCommand());
        this.commandFramework.registerCommands(new VanishCommand());
        this.commandFramework.registerCommands(new HomeCommand());
        this.commandFramework.registerCommands(new HomeSetCommand());
        this.commandFramework.registerCommands(new HomeDeleteCommand());
        this.commandFramework.registerCommands(new HomeListCommand());
        this.commandFramework.registerCommands(new CondenseCommand());
        this.commandFramework.registerCommands(new RepairCommand());
        this.commandFramework.registerCommands(new RepairHandCommand());
        this.commandFramework.registerCommands(new RepairAllCommand());
        this.commandFramework.registerCommands(new KitsCommand());
        this.commandFramework.registerCommands(new KitsCreateCommand());
        this.commandFramework.registerCommands(new KitsDeleteCommand());
        this.commandFramework.registerCommands(new KitsPreviewCommand());
        this.commandFramework.registerCommands(new EnchantCommand());
        this.commandFramework.registerCommands(new GiveCommand());
        this.commandFramework.registerCommands(new FlyCommand());
        this.commandFramework.registerCommands(new EconomyCommand());
        this.commandFramework.registerCommands(new GemmesCommand());
        this.commandFramework.registerCommands(new GemmesAddCommand());
        this.commandFramework.registerCommands(new GemmesSetCommand());
        this.commandFramework.registerCommands(new GemmesTakeCommand());
        this.commandFramework.registerCommands(new GemmesResetCommand());
        this.commandFramework.registerCommands(new VotepartyCommand());
        this.commandFramework.registerCommands(new VotepartyAddCommand());
        this.commandFramework.registerCommands(new VotepartyAddCommand());
        this.commandFramework.registerCommands(new ClearInventoryCommand());
        this.commandFramework.registerCommands(new IgnoreCommand());
        this.commandFramework.registerCommands(new PubCommand());
        this.commandFramework.registerCommands(new TopCommand());
        this.commandFramework.registerCommands(new HomeSetmaxCommand());
        this.commandFramework.registerCommands(new MailCommand());
        this.commandFramework.registerCommands(new MailTestCommand());
        this.commandFramework.registerCommands(new TimeDayCommand());
        this.commandFramework.registerCommands(new TimeNightCommand());
    }
}
