name: ValorEssentials
api-version: 1.20
version: 2.0.1
author: Kalipso
main: fr.kalipso.valorsky.hEssentials
softdepend:
  - Vault
commands:
  msg:
    description: Envoie un message privé à un joueur
    aliases: [m, tell, pm, message]
  response:
    description: Répond à un message privé à un joueur
    aliases: [r, reply]
  enchant:
    description: Enchant l'item en main
    aliases: [enchantment]
  teleport:
    description: Teleporte a un joueur
    aliases: [tp]