name: hEssentials
api-version: 1.21
version: 2.0.0
author: Kalipso
main: fr.kalipso.hexael.hEssentials
depend: [Vault]
commands:
  msg:
    description: Envoie un message privé à un joueur
    aliases: [m, tell, pm, message]
  response:
    description: Répond à un message privé à un joueur
    aliases: [r, reply]
  enchant:
    description: Enchant l'item en main
    aliases: [enchantment]
  teleport:
    description: Teleporte a un joueur
    aliases: [tp]